### ISSUE TITLE
Google 日历，导入后丢失提醒

### ISSUE THREAD

**Issue by txyyh** [SunsetYe66/ClasstableToIcal#1]
![20200330100522](https://user-images.githubusercontent.com/41893946/77868575-566a5680-726e-11ea-8036-d6ef9dd7535a.png)
![20200330100710](https://user-images.githubusercontent.com/41893946/77868580-5b2f0a80-726e-11ea-91cb-aff4ea14a706.png)
如图

**Comment by SunsetYe66** [comment]
很抱歉，这个问题暂时无法修复……在尝试适配 Google 的格式失败之后，我在 Google Support Forum 里发现，Google Calendar 在导入 ics 文件的时候会丢弃掉所有的提醒。

更深层的解释：每个提醒都有自己的 uid 和 alarm-uid，但是谷歌日历只接受自己已经生成过的 uid，目前程序里生成 uid 所使用的方法只是一个随机库，无法满足这个条件。

ref：https://support.google.com/calendar/thread/9627602?hl=en

**Comment by SunsetYe66** [comment]
@txyyh 或许你可以尝试：在一个日历里重复导入 **同一个文件** 两次来试着变相解决uid在系统中不存在的问题

**Comment by txyyh** [comment]
> @txyyh 或许你可以尝试：在一个日历里重复导入 **同一个文件** 两次来试着变相解决uid在系统中不存在的问题

无效，问题仍然存在
是Google 日历不支持吗？

**Comment by SunsetYe66** [comment]
> > @txyyh 或许你可以尝试：在一个日历里重复导入 **同一个文件** 两次来试着变相解决uid在系统中不存在的问题
> 
> 无效，问题仍然存在
> 是Google 日历不支持吗？

可以看 #2，有初步的说明。
简单说就是有个id，谷歌日历只支持它生成过的，但是我们不太好造它生成过的id，只能用随机的uid函数
