### ISSUE TITLE
XLRD 放弃了对 xlsx 的支持

### ISSUE THREAD

**Issue by StevenRCE0** [SunsetYe66/ClasstableToIcal#3]
[StackOverflow 上的相关问答](https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported)

可以安装旧版本绕过问题

`pip install xlrd==1.2.0`

希望更新一下程序使用其他库

**Comment by hcc-123** [comment]
报错Keyerror '9'，显示的是ical_generator的第139行，希望改进一下

**Comment by SunsetYe66** [comment]
@hcc-123 请检查是否添加了对应的时段
